
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
}

const SYSTEM_INSTRUCTION = `أنت "مساعد د. أشرف العزب الذكي". الدكتور أشرف استشاري جراحة العظام والمناظير وحاصل على الدكتوراة من جامعة القاهرة والزمالة الأوروبية (EBOT).

الخبرات الدولية والزمالات المرموقة التي يجب أن تذكرها بفخر:
1. زمالة جامعة جنيف (سويسرا) في علاج وترميم الكسور المعقدة (Fracture Repair).
2. زمالة جامعة هايدلبرج (ألمانيا) في جراحات المفاصل الصناعية (Artificial Joints / Arthroplasty).
3. زمالة جامعة سيول (كوريا الجنوبية) في الأطراف الصناعية المتقدمة.
4. زمالة جراحات مناظير الركبة والكتف.

العضويات الدولية:
- الجمعية الدولية للجراحة (SICOT).
- الجمعية السويسرية لتثبيت الكسور (AO Trauma).
- الجمعية الدولية لإصابات الملاعب (ISAKOS).
- الأكاديمية الأمريكية لجراحي العظام (AAOS).
- الجمعية الأوروبية للمناظير (ESSKA).

تخصصات دقيقة:
- استبدال المفاصل (Prosthetics).
- علاج الكسور والتشوهات (Trauma).
- إصابات الملاعب والرباط الصليبي (Sports Medicine).
- علاج الألم التداخلي.

تعليمات الرد:
- تحدث بلهجة مصرية مهذبة واحترافية.
- لا تصف أدوية إطلاقاً.
- أكد دائماً على أهمية الكشف السريري.
- الفروع: (القاهرة: التجمع الخامس، المنصورة: ميدان المحطة، السنبلاوين: أرض المحلج).`;

export const getMedicalAdvice = async (history: ChatMessage[], useSearch = false, useMaps = false) => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    let modelName = 'gemini-3-pro-preview'; 
    const tools: any[] = [];
    
    if (useSearch) tools.push({ googleSearch: {} });
    if (useMaps) {
      modelName = 'gemini-2.5-flash-lite-latest';
      tools.push({ googleMaps: {} });
    }

    const formattedContents = history
      .filter((m, index) => !(index === 0 && m.role === 'model'))
      .map(m => ({
        role: m.role,
        parts: [{ text: m.text }]
      }));

    if (formattedContents.length === 0) {
      return { text: "أهلاً بك في عيادة د. أشرف العزب، كيف يمكنني مساعدتك طبياً اليوم؟", grounding: [] };
    }

    const response: GenerateContentResponse = await ai.models.generateContent({
      model: modelName,
      contents: formattedContents,
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        tools: tools.length > 0 ? tools : undefined,
        temperature: 0.7,
      }
    });

    const text = response.text;
    if (!text) throw new Error("Empty response from AI");

    return {
      text: text,
      grounding: response.candidates?.[0]?.groundingMetadata?.groundingChunks || []
    };
  } catch (error: any) {
    console.error("Gemini Critical Error:", error);
    return { 
      text: "عذراً، واجهت مشكلة في معالجة طلبك حالياً. يمكنك تكرار السؤال أو الاتصال بالعيادة مباشرة للحصول على إجابة فورية من الفريق الطبي.", 
      grounding: [] 
    };
  }
};

export const editMedicalImage = async (base64Image: string, prompt: string): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Image,
            mimeType: 'image/jpeg',
          },
        },
        {
          text: prompt,
        },
      ],
    },
  });

  if (response.candidates && response.candidates.length > 0) {
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }
  }
  throw new Error("No image was generated by the model");
};

export const generateMedicalVideo = async (base64Image: string, prompt: string, aspectRatio: '16:9' | '9:16' = '16:9'): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  let operation = await ai.models.generateVideos({
    model: 'veo-3.1-fast-generate-preview',
    prompt: prompt,
    image: {
      imageBytes: base64Image,
      mimeType: 'image/jpeg',
    },
    config: {
      numberOfVideos: 1,
      resolution: '720p',
      aspectRatio: aspectRatio
    }
  });

  while (!operation.done) {
    await new Promise(resolve => setTimeout(resolve, 10000));
    operation = await ai.operations.getVideosOperation({ operation: operation });
  }

  const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
  if (!downloadLink) throw new Error("Video generation failed or URI not found");
  
  const fetchResponse = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
  const blob = await fetchResponse.blob();
  return URL.createObjectURL(blob);
};
